"""Resolve (sample_id, fov_id, country) to a per-FOV count for either of two metrics, and to a
whole-slide baseline (computed over every FOV on the slide, including the target), reading only
precomputed detection output already sitting in GCS -- never an image.

**Two metrics, chosen by the `metric` argument:**
- `"n_spots_detected"` (default) -- the raw count of candidate fluorescent-spot crops *before*
  ML filtering. Chosen over `n_rbcs` because it's mechanistically the metric a bright
  overexposure halo would inflate: these crops come from thresholding local maxima in the same
  blue-channel intensity map the halo lives in.
- `"n_positives"` -- the count of crops the ML classifier actually confirmed as a parasite, per
  FOV. Added to test a different hypothesis: does the halo artifact inflate *confirmed
  parasites*, not just raw candidate crops? (If the classifier correctly rejects halo-caused
  candidates, this should show a much weaker -- or no -- separation between ground-truth
  groups than `n_spots_detected` does; see `data/results/crop-outlier-approach/README.md`'s
  comparison section for the actual result.)

This deliberately reads the `detection_results/` prefix that `src/gcs_fov.py` and
`src/gcs_fov_multi.py` avoid on purpose (they resolve *raw* images, upstream of any model). That
tree isn't documented anywhere in this repo; the layout below was confirmed by browsing the
buckets directly (`gcloud storage ls`/`cat`), not by reading any existing code:

- Liberia (`gs://liberia-2025`) and Tanzania (`gs://tanzania_02032026`) both have
  `detection_results/<...>/<model_version>/<slide_folder>/fov_summary.csv`, one row per
  `fov_id`, with both an `n_spots_detected` and an `n_positives` column.
    * Liberia's slide folder is the same `_Blue` folder `src.gcs_fov.find_slide_blue_folder`
      already resolves, with the `_Blue` suffix stripped, under
      `detection_results/LB25-<batch>/<model_version>/`.
    * Tanzania's slide folder is `sample_id` directly under
      `detection_results/<model_version>/` -- no box-probing needed (unlike raw-image
      resolution), since this tree isn't nested under a box.
    * Verified `fov_id` here uses the exact same raster addressing as the labels CSV (checked
      LB25-D10's sparse-gap pattern against `gcs_fov.py`'s stride-18/ColumnCount=13 special
      case) -- safe to join directly, no row/col decoding needed.
    * Verified `n_spots_detected` is identical across every model-version run folder for a
      slide (the upstream spot-finding step is shared); `n_positives` legitimately *does*
      depend on which classifier produced it, since that's the thing that differs between
      model versions -- this standardizes on one folder, `MODEL_VERSION`, per country, for
      both metrics.
    * Tanzania fallback, added after finding `tanzania_02032026`'s own `detection_results/` tree
      is missing 146 slides that were never mirrored there (94 of `TZ2025-Box1`'s 98 slides, 52
      of `Box5`'s 99) -- `gs://malaria-annotation-web` (the annotation tool's bucket) turns out
      to hold `samples/<sample_id>/fov_summary.csv` for every one of those 146 gap slides.
      Tried second, after the primary `tanzania_02032026` lookup returns nothing, never
      instead of it.

      **Correction (2026-08-12).** This bullet previously claimed the annotation-bucket copy was
      "byte-for-byte identical to `tanzania_02032026`'s own copy on a sample that has both
      (`RUB-62501326`: 324/324 `n_spots_detected` values match)". That claim was wrong on both
      counts and is retracted: `RUB-62501326` has a `spots.csv` but *no* `fov_summary.csv` in the
      annotation bucket, so it never had two copies to compare -- the citation was conflated with
      the separate `spots.csv` row-count check below, which did legitimately use that slide. Where
      two copies really do exist, they are never byte-identical. Re-checked on all 8 slides in
      this analysis's TZ label set that have both:
        - `n_spots_detected`  -- identical per-FOV, 8/8 slides
        - `n_spots_filtered`  -- identical per-FOV, 8/8 slides
        - `n_positives`       -- differs on 8/8, in both directions (144 vs 46, 23 vs 101, 12 vs 29)
      Cause: the annotation bucket's `fov_summary.csv` is generated by model **O2.0**, not the
      `v8_hardneg_single_t0.995` this module standardizes Tanzania on. Confirmed by
      `model_predictions/O2.0/<sample>_O2.0.parquet`, whose `positive` count reproduces the
      annotation `fov_summary.csv`'s `n_positives` exactly (54 on `KTR-72502946`, where
      `v8_hardneg_single` at t0.995 gives 83).

      **Consequence:** the fallback preserves `n_spots_detected` (and `n_spots_filtered`) exactly,
      because spot-finding and filtering are upstream of the classifier and shared across model
      versions -- so METRIC="n_spots_detected" is safe on fallback slides. But it *silently breaks*
      the one-model-version-per-country standardization the bullet above establishes, for
      `n_positives` only. Any fallback slide's `n_positives` is O2.0 while every non-fallback
      Liberia/Tanzania slide's is a t0.995 variant. See the parasite-count caveat in
      `data/results/crop-outlier-approach/README.md` for the (currently nil) numeric impact.
- Uganda (`gs://malaria-annotation-web`) has no per-FOV summary file, but
  `samples/<sample_id>/spots.csv` has the identical per-spot schema
  (`fov_id,x,y,radius,score,positive`) as Liberia/Tanzania's own `spots.csv`. **Caveat, found
  2026-08-11 and not yet fixed:** grouping this by `fov_id` and counting rows was assumed to
  reproduce `n_spots_detected`, but cross-checking `RUB-62501326` shows the row count matches
  `n_spots_filtered` exactly (324/324 FOVs) and `n_spots_detected` on zero FOVs (0/324).
  Precision about what "a sample that has both" means here, since the earlier wording implied one
  location and that ambiguity is what produced the retracted byte-identity claim above: this slide
  has `spots.csv` in `malaria-annotation-web` and `fov_summary.csv` in `tanzania_02032026` -- one
  file per bucket, not two files in one. It has no annotation-bucket `fov_summary.csv` at all.
  That is not an anomaly: the annotation bucket carries two mutually exclusive per-sample layouts,
  an older one with `spots.csv` and no `fov_summary.csv` (which `RUB-62501326` is on, and which is
  what makes it usable for this check at all) and a newer one with `fov_summary.csv` and no
  `spots.csv` -- all 146 Tanzania gap slides are on the newer one (146/146 have `fov_summary.csv`,
  0/146 have `spots.csv`, verified 2026-08-12). Note this cross-check therefore rests on a single
  slide, on the older layout; no second corroborating slide has been looked for. Uganda has no
  `fov_summary.csv`
  anywhere to source true pre-filter `n_spots_detected` from, so the 10 Uganda rows already in
  `data/results/crop-outlier-approach/results.csv` are on a different, already-partially-filtered
  metric than every Liberia/Tanzania row -- flagged, not corrected, pending a decision on whether
  `n_spots_detected` is recoverable for Uganda at all.
- `gs://malaria-annotation-web` also has a root-level `model_predictions/` prefix (noted
  2026-08-12, not read by this module): `model_predictions/<model_version>/<sample_id>_<model_
  version>.parquet`, for O1.9, O2.0, O2.1, O2.2 and v8_hardneg_single. These are *per-crop*
  classifier outputs -- columns `patch_idx,score,positive` (plus `score_recal` on the O-series),
  one row per *filtered* crop, indexing into the sample's `patches.npy`. There is no `fov_id`
  column and no `n_spots_detected`, so they cannot be aggregated into the per-FOV crop counts this
  module needs; `fov_summary.csv` remains the only per-FOV source. Useful for provenance, though:
  the row count equals `sum(n_spots_filtered)` exactly (15059 on `KTR-72502946`, identical across
  all three model versions available for it, which is what pins spot-finding/filtering as shared
  and classifier-independent), and `positive.sum()` identifies which model generated a given
  `fov_summary.csv`.
"""
import csv
import io
import statistics
import sys
import threading
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from src.gcs_fov import find_slide_blue_folder, parse_sample_id
from src.gcs_fov_multi import TZ_BUCKET, UG_BUCKET

LB_BUCKET = "liberia-2025"
LB_MODEL_VERSION = "v8_hardneg_single_t0.995"
TZ_MODEL_VERSION = "v8_hardneg_single_t0.995"

METRICS = ("n_spots_detected", "n_positives")

MAD_SCALE = 1.4826  # scales MAD to be a normal-consistent estimator of standard deviation

_COUNTRY_ALIASES = {
    "liberia": "lb", "lb": "lb",
    "tanzania": "tz", "tz": "tz",
    "uganda": "ug", "ug": "ug",
}

_client_local = threading.local()
_slide_cache = {}  # (country, sample_id, metric) -> dict[fov_id, count] | None


def _client():
    client = getattr(_client_local, "client", None)
    if client is None:
        from google.cloud import storage

        client = storage.Client()
        _client_local.client = client
    return client


def _try_download_text(bucket, blob_name):
    """Return the blob's text, or None if it doesn't exist (rather than raising) -- a missing
    detection_results tree is an expected, reportable case here, not an error.
    """
    from google.api_core.exceptions import NotFound

    blob = _client().bucket(bucket).blob(blob_name)
    try:
        return blob.download_as_text()
    except NotFound:
        return None


def _parse_fov_summary_csv(text, metric):
    reader = csv.DictReader(io.StringIO(text))
    return {int(row["fov_id"]): int(row[metric]) for row in reader}


def _parse_spots_csv_counts(text, metric):
    """Aggregate a spots.csv (sample_id,fov_id,x,y,log_radius,score,positive) per fov_id --
    row count reproduces n_spots_detected, sum of the `positive` column reproduces n_positives.
    """
    reader = csv.DictReader(io.StringIO(text))
    counts = Counter()
    if metric == "n_spots_detected":
        for row in reader:
            counts[int(row["fov_id"])] += 1
    elif metric == "n_positives":
        for row in reader:
            counts[int(row["fov_id"])] += int(row["positive"])
    else:
        raise ValueError(f"Unknown metric: {metric!r}")
    return dict(counts)


def _lb_fov_summary_blob_name(sample_id):
    batch, *_ = parse_sample_id(sample_id)
    blue_folder = find_slide_blue_folder(sample_id, bucket=LB_BUCKET)
    slide_name = blue_folder.rstrip("/").rsplit("/", 1)[-1]
    if slide_name.endswith("_Blue"):
        slide_name = slide_name[: -len("_Blue")]
    return f"detection_results/LB25-{batch}/{LB_MODEL_VERSION}/{slide_name}/fov_summary.csv"


def _tz_fov_summary_blob_name(sample_id):
    return f"detection_results/{TZ_MODEL_VERSION}/{sample_id}/fov_summary.csv"


def _annotation_fov_summary_blob_name(sample_id):
    return f"samples/{sample_id}/fov_summary.csv"


def _ug_spots_blob_name(sample_id):
    return f"samples/{sample_id}/spots.csv"


def load_slide_metric_counts_with_source(sample_id, country, metric="n_spots_detected"):
    """As `load_slide_metric_counts`, but also reports which layout actually resolved:

        "lb_detection"      | detection_results/LB25-<batch>/<model>/<slide>/fov_summary.csv
        "tz_detection"      | detection_results/<model>/<sample>/fov_summary.csv
        "annotation_bucket" | samples/<sample>/fov_summary.csv  (the Tanzania fallback)
        "ug_spots"          | samples/<sample>/spots.csv, aggregated
        "none"              | no detection results anywhere

    The primary-vs-fallback decision used to be made here and then discarded. That is fine for
    one labeled FOV and not fine for a 271-slide sweep: only 187 of the Tanzania catalog slides
    have results under `TZ_MODEL_VERSION`, and the other 84 resolve from the annotation bucket,
    which a different (older) detector produced. The robust z-score is computed *within* a
    slide, so that difference largely cancels -- but "largely" is a claim that has to stay
    auditable, so the source travels with the counts.
    """
    if metric not in METRICS:
        raise ValueError(f"Unknown metric: {metric!r}, expected one of {METRICS}")
    key_country = _COUNTRY_ALIASES.get(country.strip().lower())
    if key_country is None:
        raise ValueError(f"Unknown country: {country!r}")

    cache_key = (key_country, sample_id, metric)
    if cache_key in _slide_cache:
        return _slide_cache[cache_key]

    if key_country == "lb":
        text = _try_download_text(LB_BUCKET, _lb_fov_summary_blob_name(sample_id))
        counts = _parse_fov_summary_csv(text, metric) if text is not None else None
        source = "lb_detection" if counts is not None else "none"
    elif key_country == "tz":
        text = _try_download_text(TZ_BUCKET, _tz_fov_summary_blob_name(sample_id))
        source = "tz_detection"
        if text is None:
            # fallback: the annotation tool's bucket has fov_summary.csv for slides never
            # mirrored into tanzania_02032026's own detection_results/ tree -- see module
            # docstring's Tanzania fallback note.
            text = _try_download_text(UG_BUCKET, _annotation_fov_summary_blob_name(sample_id))
            source = "annotation_bucket"
        counts = _parse_fov_summary_csv(text, metric) if text is not None else None
        if counts is None:
            source = "none"
    elif key_country == "ug":
        text = _try_download_text(UG_BUCKET, _ug_spots_blob_name(sample_id))
        counts = _parse_spots_csv_counts(text, metric) if text is not None else None
        source = "ug_spots" if counts is not None else "none"
    else:
        raise AssertionError(key_country)  # unreachable, all _COUNTRY_ALIASES values handled above

    _slide_cache[cache_key] = (counts, source)
    return counts, source


def load_slide_metric_counts(sample_id, country, metric="n_spots_detected"):
    """Return {fov_id: count} for every FOV on this slide with detection results, for either
    `metric` ("n_spots_detected" or "n_positives" -- see module docstring), or None if this
    sample has no detection results at all. Cached per (country, sample_id, metric) since
    several labeled rows in the diverse test set share a slide.
    """
    counts, _source = load_slide_metric_counts_with_source(sample_id, country, metric)
    return counts


def robust_zscore(target_count, stats):
    """(target - median) / scaled-MAD from `slide_baseline`, or None if the MAD is unusable.

    The single definition of this statistic. It was open-coded identically in
    analyze_crop_outliers.py, analyze_boundary_negatives.py and case_study_ktr72502946.py, and
    it belongs next to `slide_baseline`, which produces its input.

    A zero MAD means more than half a slide's FOVs share the median count, so "how many MADs
    away" has no meaning. Returning None rather than an infinity forces the caller to decide,
    instead of silently flagging every FOV or silently flagging none.
    """
    mad = stats.get("mad")
    median = stats.get("median")
    if not mad or median is None:
        return None
    return (target_count - median) / mad


def ratio_to_median(target_count, stats):
    """target / median, or None when the median is zero or undefined."""
    median = stats.get("median")
    if not median:
        return None
    return target_count / median


def slide_baseline(counts):
    """Whole-slide baseline computed once per slide, over *every* FOV with detection results on
    it (the target FOV included, not left out): mean, std, median, and scaled MAD (median
    absolute deviation), plus how many FOVs contributed.

    Previously this excluded the specific FOV being scored (leave-one-out). Changed to include
    every FOV uniformly -- for slides with 300+ FOVs the numeric difference from dropping one
    value is negligible, and a single baseline per slide (computed once, reused for every FOV
    scored against it) is simpler than recomputing per target.

    Median/MAD are the primary robust statistic (see module docstring's sibling,
    analyze_crop_outliers.py, for why) -- they tolerate up to ~50% of a slide's FOVs being
    contaminated with elevated counts before breaking, unlike mean/std which even one or two such
    FOVs can already skew. Mean/std are still returned so a large divergence between the two is
    itself visible as a signal.
    """
    values = list(counts.values())
    n = len(values)
    if n == 0:
        return {"mean": None, "std": None, "median": None, "mad": None, "n_fovs": 0}

    mean = statistics.mean(values)
    std = statistics.stdev(values) if n >= 2 else 0.0
    median = statistics.median(values)
    mad = MAD_SCALE * statistics.median(abs(v - median) for v in values)
    return {"mean": mean, "std": std, "median": median, "mad": mad, "n_fovs": n}
